### ISSUE TITLE
Center does not work

### ISSUE THREAD

**Issue by nbloomf** [kisonecat/ximera#68]
Content in the center environment is put in a div with class "center", but nothing happens.

Example document here:

http://497a6980.ngrok.com/course/nbloomf/CollegeAlgebra/master/Centering

Also- should graphics in the image environment be centered? They are with pdflatex.

**Comment by kisonecat** [comment]
The CSS that I added in a9a8d97588f2bfbdd781b1242297f958747522b8 fixes this.
