### ISSUE TITLE
Problem with First question on Pythagorean Theorem 

### ISSUE THREAD

**Issue by Falther1** [kisonecat/ximera#75]
Tried to check my answer on the first question on the Pythagorean Theorem section and it looks like it just reloads the page.

**Comment by StevenGubkin** [comment]
This is due to "theta" not being interpreted as a variable by the parser.
It will be fixed shortly.  Thanks for your diligence!

**Comment by kisonecat** [comment]
This is fixed now with kisonecat/math-expressions@e71d902fdf62d63c48fe553781c1a76c31d20e83 so I am closing this issue.
