### ISSUE TITLE
Clicking on Checkbox "refreshes" the page

### ISSUE THREAD

**Issue by bartsnapp** [kisonecat/ximera#79]
Something happens something like "refreshing" if someone clicks on the checkbox.

**Comment by kisonecat** [comment]
Which checkbox?

**Comment by bartsnapp** [comment]
Ah!, Here's what happened: I put \infty as an answer. Ximera doesn't seem to know about \infty, so this is/was unanswerable. in this case if the checkbox is clicked, you have a problem.

**Comment by kisonecat** [comment]
This is fixed in 7d36039549e529cfac9eb59a0bbb7eb961604d71
