### ISSUE TITLE
latex not rendering

### ISSUE THREAD

**Issue by bartsnapp** [kisonecat/ximera#83]
In

https://ximera.osu.edu/course/mooculus/mooculus/master/textbook/indeterminateForms/digInLimitsOfTheFormNonZeroOverZero

the latex is not rendering \numOverZero
\[
\lim_{x\to -1} \frac{1}{(x+1)^2}\qquad\text{is of the form \numOverZero}
\]

**Comment by kisonecat** [comment]
I am not so surprised that math-mode inside \text inside mathjax is failing.

Some combination of ensuremath'ing the macro and movnig it outside \text
will probably work.


~jim
